project_id = "classroom-presence"
[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000
[auth]
enabled = true
enable_signup = false
password_min_length = 12
[auth.email]
enable_signup = true
enable_confirmations = true
